require('plugins')
require('options')
require('colorscheme')
require('nvimtree')
require('keymaps')
require('telescope-config')
require('treesitter')
require('lsp-saga-config')
require('lsp')
require('nvim-comment')
require('cmp-config')
require('lualine-config')
require('bufferline-config')
require('gitsigns-config')
require('diffview').setup()
require('dap-config')
require('align-config')
require('indent-line-config')
-- require('copilot').setup {}
-- require('copilot-config')
